# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # setbox1 server
  config.vm.define "nico-box-debian1" do |setbox1|
    setbox1.vm.box = "nickrem74/debian-10.9.0-vagrant"
    setbox1.vm.hostname = "nico-box-debian1"
    setbox1.vm.box_url = "nickrem74/debian-10.9.0-vagrant"
    setbox1.vm.network :private_network, ip: "192.168.5.80"
    setbox1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "nico-box-debian1"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      service sshd restart
    SHELL
    setbox1.vm.provision "shell", path: "nico_provision.sh"
  end

  config.vm.define "nico-box-debian2" do |setbox2|
    setbox2.vm.box = "centos-7.9-vagrant"
    setbox2.vm.hostname = "nico-box-debian2"
    setbox2.vm.box_url = "centos-7.9-vagrant"
    setbox2.vm.network :private_network, ip: "192.168.5.81"
    setbox2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "nico-box-debian2"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      service sshd restart
    SHELL
    setbox2.vm.provision "shell", path: "nico_provision.sh"
  end

  config.vm.define "nico-box-debian3" do |setbox3|
    setbox3.vm.box = "my-box"
    setbox3.vm.hostname = "nico-box-debian3"
    setbox3.vm.box_url = "my-box"
    setbox3.vm.network :private_network, ip: "192.168.5.82"
    setbox3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "nico-box-debian3"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      service sshd restart
    SHELL
    setbox3.vm.provision "shell", path: "nico_provision.sh"
  end

end